Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -293,31 +293,31 @@ jobs:
         run: |
           echo "time=$(date +"%Y-%m-%d-%H-%M-%S")" >> $GITHUB_OUTPUT
 
-      - name: Run Pipeline Scanner
-        shell: bash
-        run: |
-          if [ -f VeracodeScanBaseline.json ] ;
-          then
-            echo "VERACODE BASELINE FILE ALREADY EXISTS!  Running the pipeline scan and filtering the results to only NEW flaws....."
-            java -jar pipeline-scan.jar -vid ${{secrets[env.VERACODE_API_ID_SECRET_NAME]}} -vkey ${{secrets[env.VERACODE_API_SECRET_SECRET_NAME]}} --file $JAVA_ARTIFACT --fail_on_severity="Very High, High" --baseline_file VeracodeScanBaseline.json -id true -sd true -jd true -V true -jf PipelineScan-${{ steps.time.outputs.time }}.json -fjf New_Filtered_Results.json
-            echo "List of New Very High or High Flaws..."
-            cat New_Filtered_Results.json
-          else
-            echo "VERACODE BASELINE FILE DOES NOT EXIST! Running the pipeline scan......"
-            java -jar pipeline-scan.jar -vid ${{secrets[env.VERACODE_API_ID_SECRET_NAME]}} -vkey ${{secrets[env.VERACODE_API_SECRET_SECRET_NAME]}} --file $JAVA_ARTIFACT --fail_on_severity="Very High, High" -id true -sd true -jd true -V true -jf PipelineScan-${{ steps.time.outputs.time }}.json -fjf New_Filtered_Results.json || true
-            echo "List of Very High or High Flaws......"
-            cat New_Filtered_Results.json
-          fi
-          if [[ "$GITHUB_REF_NAME" != "main" && "$GITHUB_REF_NAME" != *"dependabot"* && "$BRANCH_PROTECTION" != "true" ]] ;
-          then
-            git config --local user.email $GIT_USER_EMAIL
-            git config --local user.name $GIT_USER_NAME
-            echo "Committing VeracodeScanBaseline.json file to repo, to be used by all subsequent scans......."
-            cp PipelineScan-${{ steps.time.outputs.time }}.json VeracodeScanBaseline.json
-            git add "VeracodeScanBaseline.json"
-            git commit -m "Updates VeracodeScanBaseline"
-            git push origin ${{ github.ref_name }}
-          fi
+   #   - name: Run Pipeline Scanner
+    #    shell: bash
+     #   run: |
+      #    if [ -f VeracodeScanBaseline.json ] ;
+      #    then
+      #      echo "VERACODE BASELINE FILE ALREADY EXISTS!  Running the pipeline scan and filtering the results to only NEW flaws....."
+       #     java -jar pipeline-scan.jar -vid ${{secrets[env.VERACODE_API_ID_SECRET_NAME]}} -vkey ${{secrets[env.VERACODE_API_SECRET_SECRET_NAME]}} --file $JAVA_ARTIFACT --fail_on_severity="Very High, High" --baseline_file VeracodeScanBaseline.json -id true -sd true -jd true -V true -jf PipelineScan-${{ steps.time.outputs.time }}.json -fjf New_Filtered_Results.json
+       #     echo "List of New Very High or High Flaws..."
+       #     cat New_Filtered_Results.json
+       #   else
+        #    echo "VERACODE BASELINE FILE DOES NOT EXIST! Running the pipeline scan......"
+        #    java -jar pipeline-scan.jar -vid ${{secrets[env.VERACODE_API_ID_SECRET_NAME]}} -vkey ${{secrets[env.VERACODE_API_SECRET_SECRET_NAME]}} --file $JAVA_ARTIFACT --fail_on_severity="Very High, High" -id true -sd true -jd true -V true -jf PipelineScan-${{ steps.time.outputs.time }}.json -fjf New_Filtered_Results.json || true
+        #    echo "List of Very High or High Flaws......"
+        #    cat New_Filtered_Results.json
+        #  fi
+        #  if [[ "$GITHUB_REF_NAME" != "main" && "$GITHUB_REF_NAME" != *"dependabot"* && "$BRANCH_PROTECTION" != "true" ]] ;
+        #  then
+        #    git config --local user.email $GIT_USER_EMAIL
+        #    git config --local user.name $GIT_USER_NAME
+        #    echo "Committing VeracodeScanBaseline.json file to repo, to be used by all subsequent scans......."
+        #    cp PipelineScan-${{ steps.time.outputs.time }}.json VeracodeScanBaseline.json
+        #    git add "VeracodeScanBaseline.json"
+         #   git commit -m "Updates VeracodeScanBaseline"
+         #   git push origin ${{ github.ref_name }}
+         # fi
 
       - name: Output job status
         id: set_job_status
